name: BBQOUTLETS
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_secure_storage: ^5.0.2
  implicitly_animated_reorderable_list: ^0.4.2
  material_floating_search_bar: ^0.3.7
  foldable_list: ^1.0.0
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  flutter_carousel_slider: ^1.0.8
  nb_utils: ^4.4.17
  connectivity_plus: ^2.3.0
  http: ^0.13.4
  motion_toast: ^2.1.6
  currency_icons: ^0.3.0
  flutter_spinkit: ^5.1.0
  simple_animations: ^3.1.1
  shared_preferences: ^2.0.13
  readmore: ^2.1.0
  auto_size_text: ^3.0.0
  flutter_add_to_cart_button: ^1.0.0+1
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  rolling_nav_bar: ^0.0.5-nullsafety.3
  sizer: ^2.0.15
  flutter_sizer: ^1.0.4
  pull_to_refresh: ^2.0.0
  expandable: ^5.0.1
  outline_search_bar: ^2.3.0
  flutter_staggered_grid_view: ^0.6.1
  delayed_display: ^2.0.0
  url_launcher: ^6.0.20
  lazy_load_scrollview: ^1.3.0
  flutter_automation: ^2.0.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  double_back_to_close_app: ^2.1.0
  flutter_phoenix: ^1.0.0
  marquee: ^2.2.1
  awesome_dropdown: ^0.0.4
  roundcheckbox: ^2.0.4+1
  webview_flutter: ^3.0.2
  progress_indicators: ^1.0.0
  badges: ^2.0.2
    #  group_button: ^3.1.0
  intl: ^0.17.0
    #  adaptive_dialog: ^1.1.0
  rflutter_alert: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  provider: ^6.0.2
  flutter_overlay: ^1.0.0
  progress_loading_button: ^1.1.4
  get_it: ^7.2.0
    #  async: ^2.8.1
  persistent_bottom_nav_bar: ^4.0.2
  flutter_otp_text_field: ^1.0.1


    #

  #  flutter_local_notifications: ^8.2.0
#  cloud_firestore: ^2.5.3
  quds_ui_kit: ^0.0.7+7


  ej_selector: ^1.0.1
  animated_text_kit: ^4.2.1
    #  contextmenu: ^2.0.1
  matrix4_transform: ^2.0.1
  flutter_native_splash: ^2.1.6
  another_xlider: ^1.0.1+2
  flutter_multi_slider: ^1.1.0
  flutter_staggered_animations: "^1.0.0"
  ndialog: ^4.1.1
  menu_button: ^1.4.2+1
  awesome_select: ^5.2.0
  animated_item_picker: ^1.0.4
  multi_select_flutter: ^4.1.2
  field_suggestion: ^0.2.3
  refresh_loadmore: ^2.0.5
  animated_splash_screen: ^1.2.0
  flutter_login: ^3.2.0
  share: ^2.0.4
  slide_drawer: ^1.0.3
  textfield_search: ^0.9.2
  anim_search_bar: ^2.0.2
  advanced_search: ^2.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.9
  sqflite: ^2.0.2+1
  animations: ^2.0.2
  spring: ^2.0.2
  flip_card: ^0.6.0
  flutter_neumorphic: ^3.2.0
  flutter_widget_from_html_core: ^0.8.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  change_app_package_name: ^1.1.0
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.5+2
  json_serializable: ^6.1.6
flutter_icons:
  android: true
  ios: true
  image_path: 'appIcon/bbqologomaster.png'
  image_path_ios: "appIcon/bbqologomaster.png"
  remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - MyAssets/iconsdollar/dollar-symbol.png
  - MyAssets/asset1.jpg
  - SampleJSONFile/SampleProductJson.json
  - MyAssets/plaincircle.png
  - MyAssets/catback.png
  - MyAssets/icon.png
  - MyAssets/icon1.png
  - MyAssets/asset2.jpg
  - MyAssets/asset3.jpg
  - MyAssets/asset4.jpg
  - MyAssets/asset5.jpg
  - MyAssets/livinghall.jpg
  - MyAssets/dininghall.jpg
  - MyAssets/bedroom.jpg
  - MyAssets/logo.png
  - MyAssets/top-background.png
  - MyAssets/okay.jpeg
  - MyAssets/imagebackground.jpeg
  - MyAssets/banner.jpg
  - MyAssets/gas-grill-bbq-bbq1.png
  - MyAssets/Built-inGasGrills-gasgrilltwo.png
  - MyAssets/freestandingGasGrills.png
  - BBQ_Images/brands/alfa_id_74.png
  - BBQ_Images/
  - BBQ_Images/brands/alfresco_id_62.png
  - BBQ_Images/brands/american _id_130.jpg
  - BBQ_Images/brands/american_fyre_designs_id_124.jpg
  - BBQ_Images/brands/artisan_id_63.png
  - BBQ_Images/brands/blaze_id_7.png
  - BBQ_Images/brands/chicago_id_81.jpg
  - BBQ_Images/brands/coyote_id_78.png
  - BBQ_Images/brands/delta_heat_id_39.jpg
  - BBQ_Images/brands/twin_eagle_id_41.png
  - BBQ_Images/topDeals/free_standing_grills.png
  - BBQ_Images/topDeals/gas_grill.png
  - BBQ_Images/topDeals/pallet_grills.png
  - BBQ_Images/topDeals/pizza_oven.png
  - BBQ_Images/populardepartment/accessories.png
  - BBQ_Images/populardepartment/door-and-drawers.png
  - BBQ_Images/populardepartment/fire-logs.png
  - BBQ_Images/populardepartment/fire-pit-burners_1.png
  - BBQ_Images/populardepartment/fire-pit-place.png
  - BBQ_Images/populardepartment/fire-place.png
  - BBQ_Images/populardepartment/grill.png
  - BBQ_Images/populardepartment/Heater-from-infratech1.png
  - BBQ_Images/populardepartment/island.png
  - BBQ_Images/populardepartment/patio-furniture.png
  - BBQ_Images/populardepartment/Refrigerator-from-Hestan.png
  - BBQ_Images/populardepartment/side-burners.png
  - BBQ_Images/bbqologomaster.png
  - BBQ_Images/more_less.png
  - BBQ_Images/check.png
  - BBQ_Images/load_more.png
  - BBQ_Images/wave_image.png
  - BBQ_Images/loading_gif/loading_gifs.gif
  - BBQ_Images/menu.png
  - BBQ_Images/shopping_cart.png
  - BBQ_Images/main_banner.jpg
  - BBQ_Images/banner_image.jpeg
  - BBQ_Images/banner2_footer.jpeg
  - BBQ_Images/right_arrow.png
  - BBQ_Images/facebook.png
  - BBQ_Images/youtube.png
  - BBQ_Images/twitter.png
  - BBQ_Images/yelp.png
  - BBQ_Images/instagram.png
  - appIcon/bbqologomaster.png
  - BBQ_Images/service_images/ask.jpg
  - BBQ_Images/service_images/exp.jpg
  - BBQ_Images/service_images/fin.jpg
  - BBQ_Images/service_images/freedesign.jpg
  - BBQ_Images/service_images/price.jpg
  - BBQ_Images/service_images/shipping.jpg
  - BBQ_Images/BannerData/1.png
  - BBQ_Images/BannerData/3.png
  - BBQ_Images/sparkles.png
  - BBQ_Images/clap.png
  - BBQ_Images/Fav_Icon_BBQ_Outlets.png
  - BBQ_Images/30.png
  - BBQ_Images/32.png
  - BBQ_Images/56.png
  - BBQ_Images/flame.png
  - BBQ_Images/propane.png

  # An image asset can refer to one or more resolution-specific "variants", s1ee
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
